name: 🚀 Deploy on push main

on: 
  push:
    branches:    
      - main 

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Copy .env.local to .env
      run: cp .env.local .env

    - name: 🔨 Build Project 
      run: |
        npm install
        npm run build
      env:
        CI: false
    
    - name: List output files
      run: find out/ -print

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_SECRET }}
        local-dir: out/
        exclude: |
          api_data.json
